/*TABLA PERSONA*/
CREATE TABLE `PERSONA` ( `ID` INT(10) NOT NULL , `NOMBRE` VARCHAR(25) NOT NULL , `APELLIDO` VARCHAR(25) NOT NULL , PRIMARY KEY (`ID`));

/*INSERT DE LOS DATOS MYSQL*/
INSERT INTO `PERSONA` (`ID`, `NOMBRE`) VALUES ('1', 'JOHN'), ('2', 'JON'), ('3', 'JHON'), ('4', 'JIMENA'), ('5', 'GIMENA'), ('6', 'XIMENA'), ('7', 'SMYTHE'), ('8', 'SMITH'), ('9', 'SMETH'), ('10', 'SMOT'), ('11', 'PÉREZ'), ('12', 'PEREZ'), ('13', 'PERES'), ('14', 'perez')

/*INSERT DE LOS DATOS ORACLE*/
INSERT INTO "SYSTEM"."PERSONA" (ID, NOMBRE) VALUES ('1', 'SMYTHE')
INSERT INTO "SYSTEM"."PERSONA" (ID, NOMBRE) VALUES ('2', 'SMITH')
INSERT INTO "SYSTEM"."PERSONA" (ID, NOMBRE) VALUES ('3', 'SMETH')
INSERT INTO "SYSTEM"."PERSONA" (ID, NOMBRE) VALUES ('4', 'SMOOTH')

/*CONSULTAS SOUNDEX*/
SELECT ID, NOMBRE FROM `PERSONA` WHERE SOUNDEX(`NOMBRE`) = SOUNDEX('JON');

SELECT ID, NOMBRE FROM `PERSONA` WHERE SOUNDEX(`NOMBRE`) = SOUNDEX('PEREZ');

SELECT ID, NOMBRE FROM `PERSONA` WHERE SOUNDEX(`NOMBRE`) = SOUNDEX('Ay See Dee Ci');

SELECT SOUNDEX('Ay See Dee Ci'), SOUNDEX('AC/DC');

